cudatoolkit_dep:
  - ">=9.0.0,<9.1.0a0"
  - ">=9.2.0,<9.3.0a0"
  - ">=10.0.130,<10.1.0a0"
  - ">=10.1.243,<10.2.0a0"
  - ">=10.2.89,<10.3.0a0"
cudatoolkit:
  - 9.0
  - 9.2
  - 10.0
  - 10.1
  - 10.2
c_compiler_version:    # [linux or win]
  - 5.4                # [linux or win]
cxx_compiler_version:  # [linux or win]
  - 5.4                # [linux or win]
zip_keys:
  - cudatoolkit_dep
  - cudatoolkit
