cudatoolkit_dep:
  - ">=11.0.3,<11.1.0a0"
  - ">=11.1.1,<11.2.0a0"
cudatoolkit:
  - 11.0
  - 11.1
c_compiler_version:    # [linux or win]
  - 7.3                # [linux or win]
cxx_compiler_version:  # [linux or win]
  - 7.3                # [linux or win]
zip_keys:
  - cudatoolkit_dep
  - cudatoolkit
